artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishanwalia30/UsefulDatasets/raw/main/ConsignmentPricing_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  data_path: artifacts/data_ingestion
  required_files: ['SCMS_Delivery_History_Dataset.csv']

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion
  transform_function_path: artifacts/data_transformation/transform_function.pkl
  feature_map_path: artifacts/data_transformation/feature_map.pkl
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
